### ISSUE TITLE
Resizing the window causes the ranking graph to redraw incorrectly

### ISSUE THREAD

**Issue by iltar** [soyto/soyto.github.io#57]
http://soyto.github.io/#/ranking/Spatalos

When I resize the window, the graph will be rendered bigger than the container and every resize it will become higher.

![Ranking Graph](http://i.imgur.com/cJmT1P0.png)

**Comment by iltar** [comment]
While at it, it also displays 'Elyo' instead of 'Elyos' on the top rankers.

**Comment by soyto** [comment]
Chart trouble will be followed by https://github.com/jtblin/angular-chart.js/issues/84

**Comment by iltar** [comment]
Temporary fix might be something like setting `responsive=false`  when viewing the page on a desktop. [Modernizr](http://modernizr.com/) can be used to define this.
