### ISSUE TITLE
Adding some textual info to the graph

### ISSUE THREAD

**Issue by iltar** [soyto/soyto.github.io#58]
It would be nice to see for a user what X and Y are in the graph.

http://soyto.github.io/#/ranking/Spatalos

**Comment by soyto** [comment]
![image](https://cloud.githubusercontent.com/assets/13250982/9758375/7b177538-56e6-11e5-96c7-edd6fc0ccd13.png)

I know that isn't the best solution but changing the title is easy. Next time i will expend some time on http://www.chartjs.org/ and http://jtblin.github.io/angular-chart.js/ to get the best solution.

I change the milestone to futures
