### ISSUE TITLE
« Assasin »

### ISSUE THREAD

**Issue by LyoxChan** [soyto/soyto.github.io#75]
On char page you can read Assasin of {legion_name} it's hmmm, sad in a cool project like that xD

**Comment by epicleptico** [comment]
Rofl i will fix it asap

-----Mensaje original-----
De: "LyoxChan" <notifications@github.com>
Enviado: ‎12/‎12/‎2015 20:29
Para: "soyto/soyto.github.io" <soyto.github.io@noreply.github.com>
Asunto: [soyto.github.io] « Assasin » (#75)

On char page you can read Assasin of {legion_name} it's hmmm, sad in a cool project like that xD
