### ISSUE TITLE
Server name is missed in links

### ISSUE THREAD

**Issue by mikh-abc** [soyto/soyto.github.io#82]
Server name is missed in links on pages "Elyos" and "Asmodians":
`<a ng-href="#/character//1207619" class="ng-binding" href="#/character//1207619">Parry</a>`

**Comment by soyto** [comment]
Hello there, 

Server name is always on breadcrumb, and also on title
![image](https://user-images.githubusercontent.com/13250982/30692098-66811af6-9eca-11e7-89ab-b557a7216869.png)

I think that the most important thing on each character profile page is just the caracter ifself and server is almost irrelevant.

If you have a suggestion about how to set up serverName on character profile, just go ahead and make me a PR.

Thanks!

**Comment by soyto** [comment]
Solved. Thanks a lot :+1:
